### ISSUE TITLE
Any chance of it making it to the aur?

### ISSUE THREAD

**Issue by LethalManBoob** [jothi-prasath/auto-epp#1]
Would love it :) thanks

**Comment by jothi-prasath** [comment]
i will make it soon

**Comment by jothi-prasath** [comment]
@LethalManBoob can you test this (https://aur.archlinux.org/packages/auto-epp)

**Comment by LethalManBoob** [comment]
× auto-epp.service - auto-epp - Automatic amd-pstate epp
     Loaded: loaded (/etc/systemd/system/auto-epp.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Fri 2023-08-18 18:29:12 BST; 18min ago
   Duration: 27ms
    Process: 1597 ExecStart=/usr/bin/auto-epp (code=exited, status=1/FAILURE)
   Main PID: 1597 (code=exited, status=1/FAILURE)
        CPU: 26ms

Aug 18 18:29:12 archlinux systemd[1]: auto-epp.service: Scheduled restart job, restart counter is at 5.
Aug 18 18:29:12 archlinux systemd[1]: auto-epp.service: Start request repeated too quickly.
Aug 18 18:29:12 archlinux systemd[1]: auto-epp.service: Failed with result 'exit-code'.
Aug 18 18:29:12 archlinux systemd[1]: Failed to start auto-epp - Automatic amd-pstate epp.

**Comment by LethalManBoob** [comment]
Just got an update and now it works
● auto-epp.service - auto-epp - Automatic amd-pstate epp
     Loaded: loaded (/etc/systemd/system/auto-epp.service; enabled; preset: disabled)
     Active: active (running) since Fri 2023-08-18 19:56:49 BST; 4s ago
   Main PID: 107745 (auto-epp)
      Tasks: 1 (limit: 38378)
     Memory: 5.1M
        CPU: 15ms
     CGroup: /system.slice/auto-epp.service
             └─107745 /bin/python3 /usr/bin/auto-epp

Aug 18 19:56:49 archlinux systemd[1]: Started auto-epp - Automatic amd-pstate epp.

**Comment by jothi-prasath** [comment]
can you check with 
```bash
watch -n 1 cat /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference
```

**Comment by LethalManBoob** [comment]
```
Every 1.0s: cat /sys/devices/system/cpu/cpu0/cpufreq/energy_...  archlinux: Sat Aug 19 10:41:04 2023

     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance
     balance_performance



```
